### ISSUE TITLE
Pre-processing senza risultato

### ISSUE THREAD

**Issue by luis-ipcb** [ElettraSciComp/STP-Gui#2]
Buongiorno,
per elaborare delle tomografie acquisite sulla linea SYRMEP ho un PC XEON configurato con 16GB di RAM, Windows 7 64 bit, un SSD, scheda video NVIDIA GTX960. Col vecchio STP che si appoggiava a IDL riuscivo a produrre le slice (ovviamente senza l'uso della scheda video).
Avendo visto che c'è questa nuova versione di STP, l'ho scaricata e scompattata in una cartella sull'SSD. Purtroppo però non capisco se ci sia un malfunzionamento oppure no. Ho provato anche con un PC senza svheda video NVIDIA (un portatile con chipset INTEL) ma mi da addirittura un errore di eccezione di runtime.
Tornando al PC con la NVIDIA, ho eseguito stp.exe e configurato le cartelle di lavoro. La conversione della serie di tomografie TIFF in formato TDF produce un file tdf di 1.9 GB. La fase di preview di tomografie e sinogrammi avviene correttamente ma quando passo alla finestra di pre-processing o successive il programma credo che si blocchi. Infatti, nella finestra di Dataset Info e Preview, cliccando i pulsanti di Preview riesco a vedere i sinogrammi, le tomografie, e i flat.
Nella finestra di Pre-processing, invece, dopo aver selezionato il file tdf e abilitato i flat/dark file, se clicco preview non si vede niente. Si apre una finestra che mi comunica che procede all'esecuzione del
comando scelto (preview del sinogramma) ma il processo non termina mai e resta indefinitamente aperta la piccola finestra. Dopo decine di minuti non succede niente: nessun file scritto nella cartella temp o output, nessuna immagine elaborata e nessun carico su CPU (il carico sulle GPU non so come visualizzarlo). 
Ho provato anche a saltare il pre-processing e usare il Phase Retrival, giusto per vedere se produceva un errore o file o immagini, ma niente. Stesso comportamento: una finestra aperta che segnala una elaborazione ma che non si chiude mai e non produce nulla.
Questo comportamento si verifica con tutte e tre le versioni disponibili su GitHub.
Come posso capire che problema c'è?
Grazie
Luigi

**Comment by franzpx125** [comment]
Verifichi se le dipendenze riportate qui: https://github.com/ElettraSciComp/STP-Gui#software-requirements sono state installate correttamente e dalla user's guide provi ad eseguire passo passo l'esempio 0 (scaricandosi i relativi dati d'esempio). Se riesce ad eseguire correttamente la ricostruzione di questi dati di esempio è ragionevole concludere che non ci sono problemi con il software ma con i dati con cui viene utilizzato.
